* Fsr, "yarn install" is installing some of web-vcore's deps (eg. mobx-graphlink) under "web-vcore/node_modules", rather than hoisting; we need those deps hoisted (so that NMOverwrites can be applied), so MS those folders are manually re-hoisted by Dockerfile. [will try to find the root/"proper" fix for this later]

diff --git a/Packages/deploy/@DockerBase/Dockerfile b/Packages/deploy/@DockerBase/Dockerfile
--- a/Packages/deploy/@DockerBase/Dockerfile
+++ b/Packages/deploy/@DockerBase/Dockerfile
@@ -50,3 +50,32 @@ RUN yarn install --inline-builds
 
 # moved this to package-specific dockerfiles, as "update base docker image" has (a lot) more overhead than "copy NMOverwrites/ folder" in each package, and NMOverwrites/ can change frequently 
 #COPY NMOverwrites/ /dm_repo/
+
+# fsr, "yarn install" is installing some of web-vcore's deps (eg. mobx-graphlink) under "web-vcore/node_modules", rather than hoisting;
+#		we need those deps hoisted (so that NMOverwrites can be applied), so manually re-hoist them
+# ==========
+
+# move
+# RUN mv /dm_repo/node_modules/web-vcore/node_modules/mobx-graphlink /dm_repo/node_modules/mobx-graphlink
+# RUN mv /dm_repo/node_modules/web-vcore/node_modules/graphql-feedback /dm_repo/node_modules/graphql-feedback
+# # others (needed by mobx-graphlink and such)
+# RUN mv /dm_repo/node_modules/web-vcore/node_modules/graphql-tag /dm_repo/node_modules/graphql-tag
+# check
+# RUN if [ ! -d "/dm_repo/node_modules/mobx-graphlink" ]; then echo										"The mobx-graphlink package was not found in the root node_modules folder. Fix this! (hoisting needed for NMOverwrites)"; exit 1; fi
+# RUN if [ -d "/dm_repo/node_modules/web-vcore/node_modules/mobx-graphlink" ]; then echo			"The mobx-graphlink package was found as web-vcore subdep, rather than hoisted. Fix this! (hoisting needed for NMOverwrites)"; exit 1; fi
+# RUN if [ ! -d "/dm_repo/node_modules/graphql-feedback" ]; then echo									"The graphql-feedback package was not found in the root node_modules folder. Fix this! (hoisting needed for NMOverwrites)"; exit 1; fi
+# RUN if [ -d "/dm_repo/node_modules/web-vcore/node_modules/graphql-feedback" ]; then echo		"The graphql-feedback package was found as web-vcore subdep, rather than hoisted. Fix this! (hoisting needed for NMOverwrites)"; exit 1; fi
+
+
+
+# pre-check (fails currently, which is okay -- that's why we do the below)
+#RUN if [ ! -d "/dm_repo/node_modules/mobx-graphlink" ]; then echo										"The mobx-graphlink package was not found in the root node_modules folder. Fix this! (hoisting needed for NMOverwrites)"; else echo "-1GoodA"; fi
+#RUN if [ -d "/dm_repo/node_modules/web-vcore/node_modules/mobx-graphlink" ]; then echo			"The mobx-graphlink package was found as web-vcore subdep, rather than hoisted. Fix this! (hoisting needed for NMOverwrites)"; else echo "-1GoodB"; fi
+
+#RUN mv /dm_repo/node_modules/web-vcore/node_modules/ /dm_repo/node_modules/
+RUN cp -rl --force /dm_repo/node_modules/web-vcore/node_modules/ /dm_repo/ \
+	&& rm -r /dm_repo/node_modules/web-vcore/node_modules/
+
+# post-check
+RUN if [ ! -d "/dm_repo/node_modules/mobx-graphlink" ]; then echo										"The mobx-graphlink package was not found in the root node_modules folder. Fix this! (hoisting needed for NMOverwrites)"; exit 1; else echo "Passed."; fi
+RUN if [ -d "/dm_repo/node_modules/web-vcore/node_modules/mobx-graphlink" ]; then echo			"The mobx-graphlink package was found as web-vcore subdep, rather than hoisted. Fix this! (hoisting needed for NMOverwrites)"; exit 1; else echo "Passed."; fi
